import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/app-providers/ThemeProvider/theme-provider";
import { ReactQueryClientProvider } from "../components/app-providers/ReactQueryClientProvider/index";
import { AuthContext } from "../context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const checkCookieExists = (): boolean => {
  //   if (
  //     document.cookie
  //       .split(";")
  //       .some((item) => item.trim().startsWith("rally-session="))
  //   ) {
  //     return true;
  //   }
  //   return false;
  // };

  const hasCookie = true;

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <AuthContext.Provider
            value={{
              hasCookie,
              user: {},
            }}
          > */}
          <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
          {/* </AuthContext.Provider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
